### ISSUE TITLE
.envはあげちゃだめだよー

### ISSUE THREAD

**Issue by noboji2525** [rinkohayata/test_repository#1]
情報丸見えなので消しておくか、非表示にさせてね

**Comment by rinkohayata** [comment]
## 対処法
`.gitignore`の中に隠しファイルを記述する

## プロセス
#### 失敗1
1. 単純に`.gitignore`を追加してpushしようとした
2. pushできなかった

#### 失敗2
1. リモートリポジトリとローカルリポジトリの内容を統一させた
2. `.gitignore`をpushした
3. 既にGitHubにpushしてしまったファイルには `.gitignore`が適用されなかった

#### 成功
1. (失敗2: リモートリポジトリとローカルリポジトリの内容を統一させた)
2. キャッシュを消した
　`(main)> git rm --cached ”ファイル名”`
3.  `git add *`→pushした
4. 丸見えになっていた情報を`.gitignore`で非表示にできた！
